IF NOT EXISTS (SELECT 1 
               FROM INFORMATION_SCHEMA.TABLES 
               WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'CryptoCurrency')
BEGIN
	CREATE TABLE dbo.CryptoCurrency
	(
		Id INT IDENTITY(1,1) PRIMARY KEY,
		Code VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		Symbol VARCHAR(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		Name VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		MarketCapRank INT,
		UnderSpotLight BIT NOT NULL CONSTRAINT [DF_CryptoCurrency_UnderSpotLight] DEFAULT((0)),
		DateAdded DATETIMEOFFSET NULL,
		LastTalkedAbout DATETIMEOFFSET NULL,
		Ignore BIT NOT NULL CONSTRAINT [DF_CryptoCurrency_Ignore] DEFAULT((0)),
		Hits INT NOT NULL CONSTRAINT [DF_CryptoCurrency_Hits] DEFAULT((0)),
		Details NVARCHAR(MAX) NULL
	)
END

IF NOT EXISTS (SELECT 1 
               FROM INFORMATION_SCHEMA.TABLES 
               WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'Pairs')
BEGIN
	CREATE TABLE dbo.Pairs
	(
		Id INT IDENTITY(1,1) PRIMARY KEY,
		ExchangeId TINYINT NOT NULL,
		PairId VARCHAR(50) NOT NULL,
		Token0Id VARCHAR(50) NOT NULL,
		Token0Code VARCHAR(50) NOT NULL,
		CreatedAt DATETIMEOFFSET NOT NULL
	)
END

IF NOT EXISTS (SELECT 1 
               FROM INFORMATION_SCHEMA.TABLES 
               WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'CryptoDetails')
BEGIN
	CREATE TABLE dbo.CryptoDetails
	(
		Id           INT IDENTITY(1,1) NOT NULL,
		CoinId       INT NOT NULL,
		LogDate      DATETIMEOFFSET NOT NULL,
		Volume       DECIMAL(15,2) NOT NULL,
		Price        DECIMAL(15,6) NOT NULL,
		MarketCap    DECIMAL(15,2) NOT NULL,
		Hits         INT NOT NULL,
		CONSTRAINT [PK_dbo_CryptoDetails] PRIMARY KEY CLUSTERED 
		(
			[Id] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
	)
	CREATE NONCLUSTERED INDEX [IX_dbo_CryptoDetails_LogDate] ON dbo.CryptoDetails
	(
		[LogDate] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
	CREATE NONCLUSTERED INDEX [IX_dbo_CryptoDetails_CoinId] ON dbo.CryptoDetails
	(
		[CoinId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1 
               FROM INFORMATION_SCHEMA.TABLES 
               WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'Content')
BEGIN
	CREATE TABLE dbo.Content
	(
		[Name]  VARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL PRIMARY KEY,
		[Value] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	)
END

CREATE TYPE dbo.TVP_PossibleCoins AS TABLE
(
    Code VARCHAR(50) NOT NULL,
    NewReplies INT NOT NULL
)

CREATE TYPE [dbo].[TVP_CryptoData] AS TABLE
(
    [LogDate] DATETIMEOFFSET NOT NULL,
	[Volume] DECIMAL(15, 2) NOT NULL,
	[Price] DECIMAL(15, 6) NOT NULL,
	[MarketCap] DECIMAL(15, 2) NOT NULL
)